export const strings = {
  appTitle: 'Feedbackbogen-Generator',
  toolbar: {
    save: 'Speichern',
    load: 'Laden',
    exportJson: 'Konfig exportieren',
    importJson: 'JSON importieren',
    exportNow: 'Exportieren',
    exportFormat: 'Format',
    more: 'Mehr',
    exportPdf: 'PDF / Drucken',
    exportDocx: 'DOCX',
    exportXlsx: 'XLSX',
    exportOdp: 'ODP'
  },
  keyboard: {
    save: 'Alt+S: Speichern',
    export: 'Alt+E: Export'
  },
  columns: {
    selected: 'Ausgewählt',
    categories: 'Bewertungskriterien',
    productFormats: 'Produktebene',
    export: 'Export'
  },
  kopfdaten: {
    documentTitleSection: 'Titel',
    documentTitle: 'Titel',
    titleBewertungsbogen: 'Bewertungsbogen',
    titleFeedbackbogen: 'Feedbackbogen',
    titleCustom: 'Benutzerdefiniert',
    customTitlePlaceholder: 'Eigener Titel',
    title: 'Kopfdaten (optional vorausfüllen)',
    learner: 'Name',
    learngroup: 'Lerngruppe',
    topic: 'Thema',
    date: 'Datum',
    feedback: 'Feedback / Anmerkungen',
    fieldLabel: 'Feld',
    fieldValue: 'Vorausfüllung',
    addField: 'Kopffeld hinzufügen',
    fallbackField: 'Feld',
    footerTitle: 'Fußzeile',
    signature: 'Unterschrift',
    grade: 'Bewertung'
  },
  modes: {
    full: 'Mit Skalen',
    checklist: 'Nur Checkliste'
  },
  labels: {
    remove: 'Entfernen',
    scale: 'Skala',
    add: 'Hinzufügen',
    defaultScale: 'Standard-Skala',
    addCustomItem: 'Eigenes Kriterium hinzufügen',
    customItemPlaceholder: 'Eigenes Kriterium…',
    customItemBadge: 'Eigenes Kriterium',
    removeHeaderField: 'Kopffeld entfernen',
    searchCriteria: 'Kriterien suchen',
    searchPlaceholder: 'Suchen…',
    clearSelection: 'Auswahl leeren',
    selectCategory: 'Kategorie auswählen',
    clearCategory: 'Kategorie abwählen',
    chooseProductFormats: 'Formate auswählen',
    selectedProductFormatsEmpty: 'Noch keine Produktformate ausgewählt.',
    productFormatModalTitle: 'Produktformate auswählen',
    productFormatSearch: 'Formate suchen',
    productFormatSearchPlaceholder: 'Format oder Kriterium suchen...',
    addProductFormat: 'Hinzufügen',
    removeProductFormat: 'Entfernen',
    close: 'Schließen',
    previewMode: 'Ansicht',
    previewEmpty: 'Noch keine Kriterien ausgewählt — links auswählen.',
    selectedEmpty: 'Noch keine Kriterien ausgewählt.',
    moreActions: 'Weitere Aktionen',
    mobileEdit: 'Bearbeiten',
    mobilePreview: 'Vorschau',
    mobileExport: 'Export',
    selectedCount: (n: number) => `${n} ${n === 1 ? 'Kriterium' : 'Kriterien'} ausgewählt`
  },
  a11y: {
    status: 'Statusmeldungen',
    accordionToggle: 'Abschnitt umschalten'
  },
  messages: {
    loadedYaml: 'YAML geladen.',
    yamlError: 'Fehler beim Laden/Validieren von YAML. Fallback aktiviert.',
    saved: 'Konfiguration gespeichert.',
    loaded: 'Konfiguration geladen.',
    imported: 'JSON importiert.',
    exported: 'Export gestartet...',
    customItemAdded: 'Eigenes Kriterium hinzugefügt.',
    customItemRemoved: 'Eigenes Kriterium entfernt.',
    headerFieldAdded: 'Kopffeld hinzugefügt.',
    headerFieldRemoved: 'Kopffeld entfernt.',
    productFormatAdded: 'Produktformat hinzugefügt.',
    productFormatRemoved: 'Produktformat entfernt.'
  }
} as const;
